# Generated by Django 3.0.9 on 2020-08-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champion', '0002_link_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='locale',
            field=models.CharField(blank=True, choices=[('en-US', 'American'), ('en-AU', 'Australian'), ('nl-BE', 'Belgian'), ('en-CA', 'Canadian'), ('zh', 'Chinese'), ('zh-HK', 'Chinese Hongkong'), ('zh-CN', 'Chinese Simplified'), ('zh-SG', 'Chinese Singapore'), ('zh-TW', 'Chinese Traditional'), ('en-BZ', 'English Belize'), ('en-029', 'English Caribbean'), ('en-IE', 'English Ire'), ('en-JM', 'English Jamaica'), ('en-NZ', 'English Nz'), ('en-ZA', 'English South Africa'), ('en-TT', 'English Trinidad Y Tobago'), ('en-GB', 'English Uk'), ('fr-BE', 'French Belgian'), ('fr-CA', 'French Canadian'), ('fr-LU', 'French Luxembourg'), ('fr-CH', 'French Swiss'), ('de-AT', 'German Austrian'), ('de-LI', 'German Lichtenstein'), ('de-LU', 'German Luxembourg'), ('de-CH', 'German Swiss'), ('it-CH', 'Italian Swiss'), ('no', 'Norwegian'), ('nb-NO', 'Norwegian Bokmal'), ('nn-NO', 'Norwegian Nynorsk'), ('pt-BR', 'Portuguese Brazilian'), ('es-AR', 'Spanish Argentina'), ('es-BO', 'Spanish Bolivia'), ('es-CL', 'Spanish Chile'), ('es-CO', 'Spanish Colombia'), ('es-CR', 'Spanish Costa Rica'), ('es-DO', 'Spanish Dominican Republic'), ('es-EC', 'Spanish Ecuador'), ('es-SV', 'Spanish El Salvador'), ('es-GT', 'Spanish Guatemala'), ('es-HN', 'Spanish Honduras'), ('es-MX', 'Spanish Mexican'), ('es-ES', 'Spanish Modern'), ('es-NI', 'Spanish Nicaragua'), ('es-PA', 'Spanish Panama'), ('es-PY', 'Spanish Paraguay'), ('es-PE', 'Spanish Peru'), ('es-PR', 'Spanish Puerto Rico'), ('es-UY', 'Spanish Uruguay'), ('es-VE', 'Spanish Venezuela'), ('sv-FI', 'Swedish Finland')], max_length=6),
        ),
    ]
