# Generated by Django 3.0.9 on 2020-08-20 08:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mvp_id', models.CharField(blank=True, help_text='Please enter digits. ex) 1234567', max_length=7, validators=[django.core.validators.RegexValidator('\\d{4,7}')])),
                ('docs_tag', models.CharField(blank=True, help_text='Docs Champion Identification Tag. ex) AZ-MVP-1234567', max_length=15, validators=[django.core.validators.RegexValidator('[a-zA-Z]{2,3}-[mM][vV][pP]-\\d{4,7}')])),
                ('bio', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
