# Generated by Django 3.0.9 on 2020-08-27 08:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='docs_tag',
            field=models.CharField(blank=True, help_text='Docs Champion Identification Tag. ex) AZ-MVP-1234567', max_length=20, validators=[django.core.validators.RegexValidator('[a-zA-Z]{2,5}-[mM][vV][pP]-\\d{4,7}')]),
        ),
    ]
