# Generated by Django 3.0.9 on 2020-08-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='prefer_locale',
            field=models.CharField(blank=True, choices=[('en-US', 'American (en-US)'), ('ko-KR', 'Korea, Republic Of (ko-KR)')], max_length=6),
        ),
    ]
